"""Schema update

Revision ID: 80ab5f69aecd
Revises: 
Create Date: 2026-01-31 16:08:35.027756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ab5f69aecd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Get database connection and inspector to check for existing columns
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check if 'deleted' column already exists in 'project_products'
    columns_project_products = [c['name'] for c in inspector.get_columns('project_products')]
    if 'deleted' not in columns_project_products:
        # Add deleted column as nullable first
        with op.batch_alter_table('project_products', schema=None) as batch_op:
            batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # Check if 'deleted' column already exists in 'projects'
    columns_projects = [c['name'] for c in inspector.get_columns('projects')]
    if 'deleted' not in columns_projects:
        with op.batch_alter_table('projects', schema=None) as batch_op:
            batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # Update existing rows to have deleted=False
    op.execute("UPDATE project_products SET deleted = 0 WHERE deleted IS NULL")
    op.execute("UPDATE projects SET deleted = 0 WHERE deleted IS NULL")

    # Now make the columns NOT NULL
    with op.batch_alter_table('project_products', schema=None) as batch_op:
        batch_op.alter_column('deleted', nullable=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('deleted', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('project_products', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
