import tempfile
from datetime import datetime, timezone
from flask import send_file
import json as JSON_py
from endpoints.api.projects.shared.dxf_utils import new_doc_mm
from .shared import generate_sails_layout

def get_metadata():
    return {
        "id": "work_model",
        "name": "Work Model",
        "type": "dxf"
    }

def generate(project, **kwargs):
    """
    Generates a DXF plot file for the SHADE_SAIL product.
    """
    project_name = project.get("general", {}).get("name", "Unnamed")
    filename = f"{project_name}_workmodel.dxf"
    return generate_dxf(project, filename)

def _escape_mtext(text):
    """Escape special characters for DXF MTEXT content."""
    if not text:
        return ""
    return text.replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}")

def add_entities_to_msp(msp, entities):
    for e in entities:
        etype = e.get("type")
        if etype == "line":
             msp.add_line(e["start"], e["end"], dxfattribs=e.get("dxfattribs"))
        elif etype == "circle":
             msp.add_circle(e["center"], e["radius"], dxfattribs=e.get("dxfattribs"))
        elif etype == "point":
             msp.add_point(e["location"], dxfattribs=e.get("dxfattribs"))
        elif etype == "text":
             msp.add_text(e["text"], dxfattribs=e.get("dxfattribs")).set_placement(e["location"])
        elif etype == "mtext":
             m = msp.add_mtext(e["text"], dxfattribs=e.get("dxfattribs"))
             if "location" in e:
                 m.set_location(e["location"], attachment_point=e.get("attachment_point", 1))

def generate_dxf(project, download_name: str):
    """Lean DXF: accepts a standalone plain project dict and draws sails."""
    doc, msp = new_doc_mm()
    
    # 1. Generate Sails Layout
    layout_results = generate_sails_layout(project)
    
    # 2. Add Project Title and JSON Dump
    gen = project.get("general") or {}
    project_name = gen.get("name") or "Unnamed"
    products_list = project.get("products") or []
    project_desc = f"Project: {project_name} | Sails: {len(products_list)}"
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    msp.add_mtext(project_desc, dxfattribs={"layer": "AD_INFO", "char_height": 1000}).set_location((-3000, 6000))
    msp.add_mtext(f"Generated by AutoDraw v00.02 at {date}", dxfattribs={"layer": "AD_INFO", "char_height": 500}).set_location((-3000, 4500))
    
    json_str = JSON_py.dumps(project, indent=2)
    msp.add_mtext(_escape_mtext(json_str), dxfattribs={"layer": "AD_INFO", "char_height": 20}).set_location((-4000, 3500))

    # 3. Iterate layout results to draw sails and add Sail Title/Details
    for item in layout_results:
        entities = item['entities']
        x_offset = item['x_offset']
        pp = item['product']
        idx = item['product_index']
        geo = item['geometry']
        point_count = geo['point_count']
        
        # Sail Title
        product_title = f"Sail: {pp.get('productIndex', idx)} | {pp.get('name') or 'Unnamed'} | Points: {point_count}"
        msp.add_mtext(product_title, dxfattribs={"layer": "AD_INFO", "char_height": 300}).set_location((x_offset - 3000, 3000))
        
        # Sail Details
        edge_meter = geo.get('edge_meter', 0)
        perimeter = geo.get('perimeter', 0)
        product_details = f"Material: {geo.get('fabric_type', '')} {geo.get('colour', '')} | Perimeter: {int(perimeter)}mm | Edge Meter: {edge_meter}m"
        msp.add_mtext(product_details, dxfattribs={"layer": "AD_INFO", "char_height": 200}).set_location((x_offset - 3000, 2600))
        
        # Add generated drawing entities
        add_entities_to_msp(msp, entities)
        
        # Add algorithm legend to the right of the sail
        min_x, min_y, max_x, max_y = geo['bbox']
        sail_width = max_x - min_x
        legend_x = x_offset + sail_width + 500  # 500mm to the right of sail
        legend_y = max_y  # Start at top
        legend_spacing = 400  # Spacing between legend entries
        
        msp.add_mtext("WORKPOINT ALGORITHMS", dxfattribs={"layer": "AD_INFO", "char_height": 200}).set_location((legend_x, legend_y))
        legend_y -= legend_spacing
        
        # Color 1 = Red = Centroid
        msp.add_line((legend_x, legend_y), (legend_x + 400, legend_y), dxfattribs={"layer": "AD_WORKMODEL_CENTROID", "color": 1})
        msp.add_mtext("Centroid", dxfattribs={"layer": "AD_INFO", "char_height": 150}).set_location((legend_x + 500, legend_y + 50))
        legend_y -= legend_spacing
        
        # Color 6 = Magenta = Bisect
        msp.add_line((legend_x, legend_y), (legend_x + 400, legend_y), dxfattribs={"layer": "AD_WORKMODEL_BISECT", "color": 6})
        msp.add_mtext("Bisect", dxfattribs={"layer": "AD_INFO", "char_height": 150}).set_location((legend_x + 500, legend_y + 50))
        legend_y -= legend_spacing
        
        # Color 3 = Green = Area Centroid
        msp.add_line((legend_x, legend_y), (legend_x + 400, legend_y), dxfattribs={"layer": "AD_WORKMODEL_AREA", "color": 3})
        msp.add_mtext("Area Centroid", dxfattribs={"layer": "AD_INFO", "char_height": 150}).set_location((legend_x + 500, legend_y + 50))
        legend_y -= legend_spacing
        
        # Color 4 = Cyan = Midpoint
        msp.add_line((legend_x, legend_y), (legend_x + 400, legend_y), dxfattribs={"layer": "AD_WORKMODEL_MIDPOINT", "color": 4})
        msp.add_mtext("Midpoint", dxfattribs={"layer": "AD_INFO", "char_height": 150}).set_location((legend_x + 500, legend_y + 50))
        legend_y -= legend_spacing
        
        # Color 5 = Blue = Weighted (Edge Tension)
        msp.add_line((legend_x, legend_y), (legend_x + 400, legend_y), dxfattribs={"layer": "AD_WORKMODEL_WEIGHTED", "color": 5})
        msp.add_mtext("Weighted (Edge Tension)", dxfattribs={"layer": "AD_INFO", "char_height": 150}).set_location((legend_x + 500, legend_y + 50))
        legend_y -= legend_spacing
        
        # Color 2 = Yellow = Minimal Surface
        msp.add_line((legend_x, legend_y), (legend_x + 400, legend_y), dxfattribs={"layer": "AD_WORKMODEL_MINIMAL", "color": 2})
        msp.add_mtext("Minimal Surface", dxfattribs={"layer": "AD_INFO", "char_height": 150}).set_location((legend_x + 500, legend_y + 50))
        legend_y -= legend_spacing
        
        # Color 30 = Orange = Bisect-Rotate
        msp.add_line((legend_x, legend_y), (legend_x + 400, legend_y), dxfattribs={"layer": "AD_WORKMODEL_BISECT_ROTATE", "color": 30})
        msp.add_mtext("Bisect-Rotate", dxfattribs={"layer": "AD_INFO", "char_height": 150}).set_location((legend_x + 500, legend_y + 50))

    tmp = tempfile.NamedTemporaryFile(suffix=".dxf", delete=False)
    tmp_path = tmp.name
    tmp.close()
    doc.saveas(tmp_path)

    return send_file(
        tmp_path,
        mimetype="application/dxf",
        as_attachment=True,
        download_name=download_name,
        max_age=0,
        etag=False,
        conditional=False,
        last_modified=None,
    )
